#+LANGUAGE: de
#+OPTIONS: html5-fancy:t
#+OPTIONS: toc:nil
#+OPTIONS: tex:t
#+HTML_DOCTYPE: xhtml5
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/home/orm/.config/emacs/org-mode/ox-custom/css/org-manual-style.css" />
#+INFOJS_OPT: path:scripts/org-info-de.js
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX: \setlength\parindent{0pt}
#+LATEX_HEADER: \usepackage[top=0.5cm, left=2cm, bottom=0.5cm, right=2cm]{geometry}
#+LATEX_HEADER: \usepackage{fontspec} % For loading fonts
#+LATEX_HEADER: \defaultfontfeatures{Mapping=tex-text}
#+LATEX_HEADER: \setmainfont[Scale=0.9]{Calibri}
#+LATEX_HEADER: \setsansfont[Scale=0.9]{Calibri}[Scale=MatchLowercase]
#+LATEX_HEADER: \setmonofont[Scale=0.7]{DejaVu Sans Mono}[Scale=MatchLowercase]
#+TITLE: README.org


* clamps-install

  Scripts for the installation of [[https://github.com/ormf/clamps][clamps]].

* Linux Installation
** Dependencies
   Please download the following programs using the package manager
   of your Linux Distribution.

   - Gnu Emacs

   - LilyPond (optional)

   - Jack

   - SBCL
     
** Fresh install

   This installation method installs everything necessary to run
   clamps in Emacs. It will install the following things:

   - Emacs Configuration

     Installing the contents of =emacs.d= of the repository into
     =$HOME/.emacs.d=

   - Miscellaneous config files

     It will copy the following files from the repo into the user's
     =$HOME= folder:

     =incudinerc= to =$HOME/.incudinerc=

     =cminit.lisp= to =$HOME/.cminit.lisp=

   - Quicklisp

     Quicklisp will be installed into its default location
     =$HOME/quicklisp=
   
   - Local Quicklisp Packages

     The following local Quicklisp Packages will be downloaded and
     installed:

     =$HOME/quicklisp/local-projects/incudine=
   
     =$HOME/quicklisp/local-projects/cm=

     =$HOME/quicklisp/local-projects/fomus=
   
     =$HOME/quicklisp/local-projects/ats-cuda=
   
*** Preparation

    IMPORTANT NOTE: Before installation make sure, the files and
    folders mentioned in [[Fresh install]] are backed up and the orginal
    files are removed as they will be overwritten without warning!
    
    - Open a terminal and issue
      #+BEGIN_SRC sh
        cd /tmp
        git clone https://github.com/ormf/clamps-install.git
        cd clamps-install
      #+END_SRC

    - To make sure the files don't exist in their defalut location you
      can remove all files which will be overwritten without warning
      with the command

      =sh clean.sh=

    - The fresh installation is done with the command

      =sh clamps-install.sh=

      This will take a couple of minutes. If everything worked, Emacs
      should be started at the end of the process and should show a
      window split in half with a Common Lisp REPL in the lower half.

*** Installing
    
    =sh clamps-install=

